<?php

$lang = array(
	'__app_donate'	=> "Donate",
	'module__donate_donate' => "Donate",
	
	/* !ACP Menu */
	'menutab__donate' => "Donate",
	'menutab__donate_icon' => "money",
	'menu__donate_settings' => "Settings",
	'menu__donate_settings_settings' => "Settings",
	'menu__donate_donations' => "Donations",
	'menu__donate_donations_items' => "Items",
	'menu__donate_donations_transactions' => "Transactions",
	'menu__donate_donations_subscriptions' => "Subscriptions",
	
	/* !ACP Restrictions */
	'r__donate_settings' => "Settings",
	'r__donate_settings_manage' => "Can access settings?",
	'r__donate_settings_general_manage' => "Can manage general settings?",
	'r__donate_settings_paypal_manage' => "Can manage PayPal settings?",
	'r__donate_settings_sourcebans_manage' => "Can manage Sourcebans settings?",
	'r__donate_settings_csgostore_manage' => "Can manage CS:GO store settings?",
	'r__donate_donations_items' => "Items",
	'r__donate_donations_items_manage' => "Can view items?",
	'r__donate_donations_items_add' => "Can add items?",
	'r__donate_donations_items_edit' => "Can edit items?",
	'r__donate_donations_transactions' => "Transactions",
	'r__donate_donations_transactions_manage' => "Can view transactions?",
	'r__donate_donations_transactions_add' => "Can add transactions?",
	'r__donate_donations_transactions_edit' => "Can edit transactions?",
	'r__donate_donations_subscriptions' => "Subscriptions",
	'r__donate_donations_subscriptions_manage' => "Can view subscriptions?",
	'r__donate_donations_subscriptions_add' => "Can add subscriptions?",
	'r__donate_donations_subscriptions_edit' => "Can edit subscriptions?",
	
	/* !ACP General Settings */
	'donate_settings_general' => "General",
	'donate_settings_general_settings' => "General Settings",
	'acplogs__donate_settings_general' => "Edited Donate General Settings",
	'donate_log_enabled' => "Enable Logging?",
	'donate_log_enabled_desc' => "Events such as orders being created, payments being made, or subscriptions being canceled will be logged for future reference.",
	'donate_donation_goal' => "Donation Goal",
	'donate_provider_smallprint' => "Checkout Terms & Conditions",
	'donate_provider_smallprint_desc' => "Any terms and conditions you want to show on the checkout's pay step, or that payment providers (e.g. PayPal) may require.",
	
	/* !ACP PayPal Settings */
	'donate_settings_paypal' => "PayPal",
	'donate_settings_paypal_settings' => "PayPal Settings",
	'acplogs__donate_settings_paypal' => "Edited Donate PayPal Settings",
	'donate_paypal_email' => "Account Email",
	'donate_settings_paypal_api' => "API Credentials",
	'donate_paypal_api_sandbox_enabled' => "Use Sandbox Environment?",
	'donate_paypal_api_sandbox_enabled_desc' => "In order to test the application the PayPal API sandbox environment will be used instead of production. Sandbox accounts must be used while this is enabled.",
	'donate_paypal_api_sandbox_clientid' => "Sandbox Client Id",
	'donate_paypal_api_sandbox_secret' => "Sandbox Secret",
	'donate_paypal_api_live_clientid' => "Production Client Id",
	'donate_paypal_api_live_secret' => "Production Secret",
	'donate_settings_paypal_eventlistener' => "Event Listener",
	'donate_paypal_ipn_enabled' => "IPN",
	'donate_paypal_webhook_enabled' => "Webhook",
	'donate_paypal_webhook_id' => "Webhook Id",
	
	/* !ACP Sourcebans Settings */
	'donate_settings_sourcebans' => "Sourcebans",
	'donate_settings_sourcebans_settings' => "Sourcebans Settings",
	'acplogs__donate_settings_sourcebans' => "Edited Donate Sourcebans Settings",
	'donate_sourcebans_db_host' => "Database Host",
	'donate_sourcebans_db_user' => "Database Username",
	'donate_sourcebans_db_pass' => "Database Password",
	'donate_sourcebans_db_database' => "Database Name",
	'donate_sourcebans_db_port' => "Database Port",
	'donate_sourcebans_groups' => "Assigned Groups",
	'donate_sourcebans_groups_desc' => "NOTE: You must use the JSON format.<br><br>For each group object the key is the IPS group id. Within the objects, \"groups\" contains the Sourcebans group names that should be set when the group perk is activated. The key is the user's starting SB group, the value is what the group should be set to. \"unset_groups\" is for special cases; it contains the assigned Sourcebans groups that should be set down to when the group perk is deactivated.<br><br><i>This is just a temporary way of editing the groups, a more user friendly way will be <span title='...Maybe'>Coming Soon&trade;</span></i>",
	
	/* !ACP CS:GO Store Settings */
	'donate_settings_csgostore' => "CS:GO Store",
	'donate_settings_csgostore_settings' => "CS:GO Store Settings",
	'acplogs__donate_settings_csgostore' => "Edited Donate CS:GO Store Settings",
	'donate_csgostore_db_host' => "Database Host",
	'donate_csgostore_db_user' => "Database Username",
	'donate_csgostore_db_pass' => "Database Password",
	'donate_csgostore_db_database' => "Database Name",
	'donate_csgostore_db_port' => "Database Port",
	
	/* !ACP Items */
	'donate_items_settings' => "Item Settings",
	'acplogs__donate_items' => "Saved Donate Item",
	'donate_items_add' => "Create New Item",
	'donate_items_name' => "Item Name",
	'donate_items_price' => "Item Price",
	'donate_items_price_detail' => "Custom Price Suffix",
	'donate_items_price_detail_desc' => "Use this if you want to display a custom suffix after the price.",
	'donate_items_color_use' => "Use an Item Color?",
	'donate_items_color' => "Item Color",
	'donate_items_desc' => "Item Description",
	'donate_items_payment_options' => "Payment Options",
	'donate_items_payment_options_paymenttype' => "Payment Type",
	'donate_items_payment_options_pricetype' => "Price Type",
	'donate_items_active_length_use' => "Use Active Length?",
	'donate_items_active_length' => "Active Length",
	'donate_items_active_length_desc' => "How long this item will be active for before it expires or renews.",
	'donate_items_active_length_time' => "Time format",
	'donate_items_enabled' => "Enabled",
	'donate_items_perks_settings' => "Perk Settings",
	'donate_items_perks' => "Perks",
	'donate_items_perksdesc' => "Perks Description",
	'donate_items_perk_member_group' => "Member Group",
	'donate_items_perk_sb_group' => "Sourcebans Group",
	'donate_items_perk_store_credits' => "Store Credits",
	'donate_items_provider_settings' => "Payment Provider Data",
	'donate_items_paypal_planid' => "PayPal Plan Id",
	
	/* !ACP Transactions */
	'donate_transactions_type' => "Type",
	'donate_transactions_type_payment' => "Payment",
	'donate_transactions_type_payment_refund' => "Refund",
	'donate_transactions_type_payment_reversal' => "Reversal",
	'donate_transactions_member' => "Member",
	'donate_transactions_amount' => "Amount",
	'donate_transactions_order' => "Order #",
	'donate_transactions_token' => "Transaction #",
	'donate_transactions_status' => "Status",
	'donate_transactions_status_paid' => "Paid",
	'donate_transactions_status_refunded' => "Refunded",
	'donate_transactions_status_reversed' => "Reversed",
	'donate_transactions_date' => "Date",
	
	/* !ACP Subscriptions */
	'acplogs__donate_subscriptions' => "Saved Donate Subscription",
	'donate_subscriptions_add' => "Add Subscription",
	'donate_subscriptions_edit' => "Edit Subscription",
	'donate_subscriptions_member' => "Member",
	'donate_subscriptions_item' => "Item",
	'donate_subscriptions_active' => "Active",
	'donate_subscriptions_inactive' => "Inactive",
	'donate_subscriptions_giftee' => "",
	'donate_subscriptions_gift' => "Gift",
	'donate_subscriptions_deactivate_date' => "Expires/Renews",
	'donate_subscriptions_date' => "Start Date",
	'donate_subscriptions_date_expire' => "Expire Date",
	'donate_subscriptions_extra_data' => "Extra Data",
	
	/* !Front-End */
	'donate_back' => "Back",
	'donate_pay' => "Confirm & Pay",
	'donate_payment_option_subscription' => "Subscription",
	'donate_payment_option_onetime' => "Single Donation",
	'donate_payment_option_subscriptionfixed' => "Subscription, Fixed",
	'donate_payment_option_subscriptionvariable' => "Subscription, Variable",
	'donate_payment_option_onetimefixed' => "Single Donation, Fixed",
	'donate_payment_option_onetimevariable' => "Single Donation, Variable",
	'donate_payment_option_fixed' => "Fixed",
	'donate_payment_option_variable' => "Variable",
	'donate_donationlist' => "Donation List",
	'donate_donationlist_latest' => "Latest Donations",
	'donate_donationlist_top' => "Top Donors",
	'donate_donationlist_total' => "Total",
	'donate_donationlist_date' => "Date",
	'donate_donationlist_member' => "Member",
	'donate_donationlist_amount' => "Amount",
	'donate_donationlist_sort_date' => "Date",
	'donate_donationlist_sort_amount' => "Amount",
	'donate_mydonations' => "My Donations",
	'donate_mydonations_menu' => "Menu",
	'donate_mydonations_overview' => "Overview",
	'donate_mydonations_overview_active' => "Active",
	'donate_mydonations_overview_inactive' => "Previous",
	'donate_mydonations_overview_pending' => "Pending",
	'donate_mydonations_payments' => "Payments",
	'donate_mydonations_cost' => "Cost",
	'donate_mydonations_type' => "Type",
	'donate_mydonations_expiresrenews' => "Expires/Renews",
	'donate_mydonations_expires' => "Expires on",
	'donate_mydonations_renews' => "Renews on",
	'donate_mydonations_date' => "Date",
	'donate_mydonations_amount' => "Amount",
	'donate_mydonations_item' => "Item",
	'donate_mydonations_order' => "Order #",
	'donate_mydonations_sort_amount' => "Amount",
	'donate_mydonations_sort_date' => "Date",
	'donate_mydonations_gift_for' => "Gift for",
	'donate_mydonations_gift_from' => "Gift from",
	'donate_checkout' => "Donation Checkout",
	'donate_checkout_choose' => "Choose",
	'donate_checkout_choose_title' => "Choose an Item",
	'donate_checkout_options' => "Options",
	'donate_checkout_options_title' => "Pick your Options",
	'donate_checkout_pay' => "Pay",
	'donate_checkout_pay_title' => "Pay the Order",
	'donate_checkout_confirm' => "Confirm",
	'donate_checkout_complete' => "Complete",
	'donate_checkout_complete_success' => "Your order is complete!",
	'donate_checkout_complete_success_desc' => "Perks are now available to use",
	'donate_checkout_complete_pending' => "Your order is currently pending",
	'donate_checkout_complete_pending_desc' => "Perks will become available when payment has been confirmed",
	'donate_checkout_complete_pending_desc_detail' => "This may take a few minutes or longer for some payment methods",
	'donate_checkout_complete_order_number' => "Order #",
	'donate_checkout_items' => "Choose an item",
	'donate_checkout_payment_options' => "Pick a Donation Option",
	'donate_checkout_amount' => "Amount to Donate",
	'donate_checkout_gift' => "Is this a Gift?",
	'donate_checkout_gift_review' => "Gift for",
	'donate_checkout_gift_member_desc' => "Search for a member",
	'donate_checkout_steam_account' => "Choose a Steam account",
	'donate_checkout_steam_account_review' => "Steam Account",
	'donate_checkout_steam_account_or' => "Or",
	'donate_checkout_steam_account_login_desc' => "Use your linked Steam account",
	'donate_checkout_steam_account_text_desc' => "Search for a Steam account",
	'donate_checkout_steam_account_text_desc_note' => "<strong>Note:</strong> Forum perks will not apply until account is linked",
	'donate_checkout_gateway_providers' => "Select a Payment Method",
	'donate_checkout_perks_review_subscription' => "Renews every <strong>%s</strong>",
	'donate_checkout_perks_review_onetime' => "Perks will last for <strong>%s</strong>",
	'donate_checkout_perks_review_credits' => "<strong>%s</strong> Credits",
	'donate_checkout_error_items' => "Please select an item",
	'donate_checkout_error_payment_options' => "Please select a donation option",
	'donate_checkout_error_gift' => "Please enter a valid member",
	'donate_checkout_error_gift_self' => "You cannot gift to yourself",
	'donate_checkout_error_steam_account' => "Please select a steam account",
	'donate_checkout_error_gateway_providers' => "Please select a payment provider",
	
	/* !Gateway Providers */
	'donate_gateway_provider_paypal' => "PayPal",
	
	/* !Time */
	'second' => "second",
	'minute' => "minute",
	'hour' => "hour",
	'day' => "day",
	'week' => "week",
	'month' => "month",
	'year' => "year",
	
	/* !Widgets */
	'block_donationGoal' => "Donation Goal",
	'block_donationGoal_desc' => "Shows the donation goal for this month",
	'block_donationGoal_month' => "%s Donations",
	'block_donationGoal_donate' => "Support the Community",
	
	/* !Notifications */
	'notifications__donate_Donate' => "Donate",
	'notifications__order_completed' => "Order completed",
	'notification__order_completed' => "Donation order is complete. %s perks are now available",
	'notifications__gifted' => "Gifted",
	'notification__gifted' => "%s has gifted you %s",
	
	/* !Online User Locations */
	'loc_donate_donationlist' => "Viewing Donation List",
	'loc_donate_mydonations' => "Viewing My Donations",
	'loc_donate_checkout'	=> "Using Donation Checkout"
);
